In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#load data set
df = pd.read_csv("../data/raw/health_risk_dataset.csv")
print("successfully loaded data set")

successfully loaded data set

In [3]:
df.head()

,Age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,hypertension_risk_score,heart_disease_risk_score,obesity_risk_score,cholesterol_risk_score
0,58,Male,Asian,Highschool,Lower-Middle,Employed,Never,0,215,5.7,...,145,136,236,6.36,8.18,51.716583,53.581369,50.796020,57.387241,51.492983
1,52,Female,White,Highschool,Middle,Employed,Former,1,143,6.7,...,30,93,150,2.00,5.63,26.096162,47.946740,23.853485,36.219202,3.984993
2,60,Male,Hispanic,Highschool,Middle,Unemployed,Never,1,57,6.4,...,36,118,195,5.07,7.51,54.830087,42.141104,38.977694,42.898797,21.793300
3,74,Female,Black,Highschool,Low,Retired,Never,0,49,3.4,...,140,139,253,5.28,9.03,60.729521,60.286946,53.579555,52.194082,22.962029
4,46,Male,White,Graduate,Middle,Retired,Never,1,109,7.2,...,160,137,184,12.74,7.20,32.778085,15.279074,18.721942,32.095465,34.296907

In [4]:
df.shape

(97297, 33)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97297 entries, 0 to 97296
Data columns (total 33 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Age                                 97297 non-null  int64
 1   gender                              97297 non-null  str
 2   ethnicity                           97297 non-null  str
 3   education_level                     97297 non-null  str
 4   income_level                        97297 non-null  str
 5   employment_status                   97297 non-null  str
 6   smoking_status                      97297 non-null  str
 7   alcohol_consumption_per_week        97297 non-null  int64
 8   physical_activity_minutes_per_week  97297 non-null  int64
 9   diet_score                          97297 non-null  float64
 10  sleep_hours_per_day                 97297 non-null  float64
 11  screen_time_hours_per_day           97297 non-null  float64
 12  family_history_diabetes             97297 non-null  int64
 13  hypertension_history                97297 non-null  int64
 14  cardiovascular_history              97297 non-null  int64
 15  bmi                                 97297 non-null  float64
 16  waist_to_hip_ratio                  97297 non-null  float64
 17  systolic_bp                         97297 non-null  int64
 18  diastolic_bp                        97297 non-null  int64
 19  heart_rate                          97297 non-null  int64
 20  cholesterol_total                   97297 non-null  int64
 21  hdl_cholesterol                     97297 non-null  int64
 22  ldl_cholesterol                     97297 non-null  int64
 23  triglycerides                       97297 non-null  int64
 24  glucose_fasting                     97297 non-null  int64
 25  glucose_postprandial                97297 non-null  int64
 26  insulin_level                       97297 non-null  float64
 27  hba1c                               97297 non-null  float64
 28  diabetes_risk_score                 97297 non-null  float64
 29  hypertension_risk_score             97297 non-null  float64
 30  heart_disease_risk_score            97297 non-null  float64
 31  obesity_risk_score                  97297 non-null  float64
 32  cholesterol_risk_score              97297 non-null  float64
dtypes: float64(12), int64(15), str(6)
memory usage: 24.5 MB

In [6]:
df.columns

Index(['Age', 'gender', 'ethnicity', 'education_level', 'income_level',
       'employment_status', 'smoking_status', 'alcohol_consumption_per_week',
       'physical_activity_minutes_per_week', 'diet_score',
       'sleep_hours_per_day', 'screen_time_hours_per_day',
       'family_history_diabetes', 'hypertension_history',
       'cardiovascular_history', 'bmi', 'waist_to_hip_ratio', 'systolic_bp',
       'diastolic_bp', 'heart_rate', 'cholesterol_total', 'hdl_cholesterol',
       'ldl_cholesterol', 'triglycerides', 'glucose_fasting',
       'glucose_postprandial', 'insulin_level', 'hba1c', 'diabetes_risk_score',
       'hypertension_risk_score', 'heart_disease_risk_score',
       'obesity_risk_score', 'cholesterol_risk_score'],
      dtype='str')

In [7]:
df.dtypes

Age                                     int64
gender                                    str
ethnicity                                 str
education_level                           str
income_level                              str
employment_status                         str
smoking_status                            str
alcohol_consumption_per_week            int64
physical_activity_minutes_per_week      int64
diet_score                            float64
sleep_hours_per_day                   float64
screen_time_hours_per_day             float64
family_history_diabetes                 int64
hypertension_history                    int64
cardiovascular_history                  int64
bmi                                   float64
waist_to_hip_ratio                    float64
systolic_bp                             int64
diastolic_bp                            int64
heart_rate                              int64
cholesterol_total                       int64
hdl_cholesterol                         int64
ldl_cholesterol                         int64
triglycerides                           int64
glucose_fasting                         int64
glucose_postprandial                    int64
insulin_level                         float64
hba1c                                 float64
diabetes_risk_score                   float64
hypertension_risk_score               float64
heart_disease_risk_score              float64
obesity_risk_score                    float64
cholesterol_risk_score                float64
dtype: object

In [8]:
df.isnull().sum()

Age                                   0
gender                                0
ethnicity                             0
education_level                       0
income_level                          0
employment_status                     0
smoking_status                        0
alcohol_consumption_per_week          0
physical_activity_minutes_per_week    0
diet_score                            0
sleep_hours_per_day                   0
screen_time_hours_per_day             0
family_history_diabetes               0
hypertension_history                  0
cardiovascular_history                0
bmi                                   0
waist_to_hip_ratio                    0
systolic_bp                           0
diastolic_bp                          0
heart_rate                            0
cholesterol_total                     0
hdl_cholesterol                       0
ldl_cholesterol                       0
triglycerides                         0
glucose_fasting                       0
glucose_postprandial                  0
insulin_level                         0
hba1c                                 0
diabetes_risk_score                   0
hypertension_risk_score               0
heart_disease_risk_score              0
obesity_risk_score                    0
cholesterol_risk_score                0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.describe()

,Age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,cardiovascular_history,bmi,...,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,hypertension_risk_score,heart_disease_risk_score,obesity_risk_score,cholesterol_risk_score
count,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,...,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000,97297.000000
mean,50.192699,2.004543,118.942886,5.995214,6.997708,5.997031,0.219657,0.250912,0.079067,25.615093,...,121.466407,111.121792,160.014348,9.063591,6.520338,41.237414,41.137170,32.063255,48.407241,26.075076
std,15.492557,1.418060,84.441920,1.780096,1.093726,2.469805,0.414017,0.433540,0.269845,3.588387,...,43.393422,13.590382,30.938915,4.956342,0.813710,10.990720,12.755572,15.412755,10.998884,13.028452
min,19.000000,0.000000,0.000000,0.000000,3.000000,0.500000,0.000000,0.000000,0.000000,15.000000,...,30.000000,60.000000,70.000000,2.000000,4.000000,1.821211,0.000000,0.000000,12.711686,0.000000
25%,38.000000,1.000000,57.000000,4.800000,6.300000,4.300000,0.000000,0.000000,0.000000,23.200000,...,91.000000,102.000000,139.000000,5.090000,5.970000,33.611350,32.136805,20.389335,40.898793,16.506114
50%,51.000000,2.000000,100.000000,6.000000,7.000000,6.000000,0.000000,0.000000,0.000000,25.600000,...,121.000000,111.000000,160.000000,8.790000,6.520000,40.773364,40.941950,30.793098,48.509658,25.497612
75%,61.000000,3.000000,160.000000,7.200000,7.700000,7.700000,0.000000,1.000000,0.000000,28.000000,...,151.000000,120.000000,181.000000,12.450000,7.070000,48.430041,49.911238,42.564698,55.928994,34.804830
max,90.000000,10.000000,833.000000,10.000000,10.000000,16.800000,1.000000,1.000000,1.000000,39.200000,...,344.000000,172.000000,287.000000,32.220000,9.800000,84.329497,92.102337,97.902483,86.832124,83.112231

In [11]:
numerical_columns = df.select_dtypes(include = ["int64", "float64"]).columns
print("Numerical columns:", numerical_columns)

Numerical columns: Index(['Age', 'alcohol_consumption_per_week',
       'physical_activity_minutes_per_week', 'diet_score',
       'sleep_hours_per_day', 'screen_time_hours_per_day',
       'family_history_diabetes', 'hypertension_history',
       'cardiovascular_history', 'bmi', 'waist_to_hip_ratio', 'systolic_bp',
       'diastolic_bp', 'heart_rate', 'cholesterol_total', 'hdl_cholesterol',
       'ldl_cholesterol', 'triglycerides', 'glucose_fasting',
       'glucose_postprandial', 'insulin_level', 'hba1c', 'diabetes_risk_score',
       'hypertension_risk_score', 'heart_disease_risk_score',
       'obesity_risk_score', 'cholesterol_risk_score'],
      dtype='str')

In [12]:
categorical_columns = df.select_dtypes(include=["object"]).columns
print("categorical_columns: ", categorical_columns)

categorical_columns:  Index(['gender', 'ethnicity', 'education_level', 'income_level',
       'employment_status', 'smoking_status'],
      dtype='str')

C:\Users\DELL\AppData\Local\Temp\ipykernel_4244\1686315913.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object"]).columns

In [14]:
target_columns = [
    "diabetes_risk_score",
    "hypertension_risk_score",
    "heart_disease_risk_score",
    "obesity_risk_score",
    "cholesterol_risk_score",
]

print(df[target_columns].head())

   diabetes_risk_score  hypertension_risk_score  heart_disease_risk_score  \
0            51.716583                53.581369                 50.796020
1            26.096162                47.946740                 23.853485
2            54.830087                42.141104                 38.977694
3            60.729521                60.286946                 53.579555
4            32.778085                15.279074                 18.721942

   obesity_risk_score  cholesterol_risk_score
0           57.387241               51.492983
1           36.219202                3.984993
2           42.898797               21.793300
3           52.194082               22.962029
4           32.095465               34.296907

## Initial Observations

- Dataset contains 97,297 records.
- Dataset has 33 columns.
- Five columns are target variables.
- There are X numerical columns.
- There are Y categorical columns.
- Missing values were found in 0
- Duplicate rows: 0
- Data appears suitable for preprocessing.